version: "3.1"

services:
  jenkins:
    build:
      context: jenkins
    image: jenkins-master
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8088:8080"
      - "50000:50000"
volumes:
  jenkins_home:


